services:
  api:
    build: ./rag
    ports:
      - "8000:8000"
    env_file: envs/.env.rag
    volumes:
      - ./rag/src:/app/src
    depends_on:
      - postgres
      - qdrant
      - parser

  parser:
    build: ./parser
    ports:
      - "8001:8000"
    env_file: envs/.env.parser
    volumes:
      - ./parser/src:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - ./.volumes/redis:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./.volumes/qdrant:/qdrant/storage

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: envs/.env.postgres
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
