services:
  api:
    build: ./rag
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      POSTGRES_URL: postgresql://codeforces:codeforces@postgres:5432/codeforces
      QDRANT_URL: http://qdrant:6333
      PARSER_BASE_URL: http://parser:8000
    depends_on:
      - postgres
      - qdrant
      - parser

  parser:
    build: ./parser
    ports:
      - "8001:8000"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./.volumes/qdrant:/qdrant/storage

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-codeforces}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-codeforces}
      POSTGRES_DB: ${POSTGRES_DB:-codeforces}
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
